use chrono::{Local, SecondsFormat};
use crate::{
    Agents,
    ApiLog,
    AskTo,
    Config,
    Error,
    EtcModels,
    LLMToken,
    Model,
    ParseError,
    ParsedSegment,
    SessionSummary,
    ToolCallError,
    ToolCallSuccess,
    count_bytes_of_llm_tokens,
    truncate_chars,
};
use flate2::Compression;
use flate2::read::{GzDecoder, GzEncoder};
use ragit_fs::{
    WriteMode,
    file_name,
    join4,
    read_bytes,
    write_bytes,
};
use regex::Regex;
use serde::{Deserialize, Serialize};
use std::io::Read;
use std::sync::LazyLock;

#[derive(Clone, Debug, Deserialize, Eq, Hash, PartialEq, Serialize)]
pub struct TurnId(pub String);

// TODO: now that `from_str` uses this regex, it needs to be more strict.
pub static TURN_ID_REGEX: LazyLock<Regex> = LazyLock::new(|| Regex::new(r".+\-(pe|tce|tcs)\-(ag|ss|uq|ui)\-(\d{6,})\-(\d{6,})$").unwrap());

pub static TURN_TIMESTAMP_REGEX: LazyLock<Regex> = LazyLock::new(|| Regex::new(r"(.+)\-(?:pe|tce|tcs)\-(?:ag|ss|uq|ui)\-.+").unwrap());

impl TurnId {
    pub fn dummy() -> TurnId {
        TurnId(String::new())
    }

    pub fn from_str(s: &str) -> Result<TurnId, Error> {
        if TURN_ID_REGEX.is_match(s) {
            Ok(TurnId(s.to_string()))
        }

        else {
            Err(Error::InvalidTurnId(s.to_string()))
        }
    }

    pub fn get_turn_summary(&self) -> TurnSummary {
        let cap = TURN_ID_REGEX.captures(&self.0).unwrap();
        let result = match cap.get(1).unwrap().as_str() {
            "pe" => TurnResultSummary::ParseError,
            "tce" => TurnResultSummary::ToolCallError,
            "tcs" => TurnResultSummary::ToolCallSuccess,
            _ => unreachable!(),
        };
        let kind = match cap.get(2).unwrap().as_str() {
            "ag" => TurnKind::Agent,
            "ss" => TurnKind::SessionStart,
            "uq" => TurnKind::UserQuestion,
            "ui" => TurnKind::UserInstruction,
            _ => unreachable!(),
        };
        let llm_len_short = cap.get(3).unwrap().as_str().parse::<u64>().unwrap();
        let llm_len_full = cap.get(4).unwrap().as_str().parse::<u64>().unwrap();
        TurnSummary { id: self.clone(), result, kind, llm_len_short, llm_len_full }
    }

    pub fn get_session_summary(&self, working_dir: &str) -> Result<SessionSummary, Error> {
        let turn = Turn::load(self, working_dir)?;
        let turn_preview = turn.preview();

        match &turn.turn_result {
            TurnResult::ToolCallSuccess(ToolCallSuccess::Write { path, content, is_summary: true, .. }) => Ok(SessionSummary {
                timestamp: turn_preview.timestamp,
                timestamp_millis: turn.timestamp_millis,
                title: file_name(path)?,
                summary: content.to_string(),
            }),

            // This is a bug in harness.
            _ => unreachable!(),
        }
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum TurnKind {
    // *Real* turns that are generated by LLMs.
    Agent,

    // The first few turns of a session are fake turns.
    SessionStart,

    UserQuestion,
    UserInstruction,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct Turn {
    pub id: TurnId,
    pub ai_thinking: Option<String>,
    pub raw_response: String,
    pub parse_result: Option<ParsedSegment>,
    pub turn_result: TurnResult,
    pub llm_elapsed_ms: u64,
    pub tool_elapsed_ms: u64,
    pub timestamp_millis: i64,  // when the turn's finished
    pub agents: Agents,
    pub etc_models: EtcModels,
    pub kind: TurnKind,
    pub api_log: ApiLog,
}

impl Turn {
    pub fn new(
        ai_thinking: Option<String>,
        raw_response: String,
        parse_result: Option<ParsedSegment>,
        turn_result: TurnResult,
        llm_elapsed_ms: u64,
        tool_elapsed_ms: u64,
        kind: TurnKind,
        config: &Config,
        api_log: ApiLog,
    ) -> Turn {
        let mut turn = Turn {
            id: TurnId::dummy(),
            ai_thinking,
            raw_response,
            parse_result,
            turn_result,
            llm_elapsed_ms,
            tool_elapsed_ms,
            timestamp_millis: Local::now().timestamp_millis(),
            agents: config.agents,
            etc_models: config.etc_models.clone(),
            kind,
            api_log,
        };
        let turn_summary = turn.summary(config);
        let turn_id = get_turn_id(turn_summary);
        turn.id = turn_id;
        turn
    }

    pub fn load(id: &TurnId, working_dir: &str) -> Result<Turn, Error> {
        let path = join4(working_dir, ".neukgu", "turns", &format!("{}.json.gz", id.0))?;
        let json = read_bytes(&path)?;
        let mut decompressed = vec![];
        let mut gz = GzDecoder::new(&json[..]);
        gz.read_to_end(&mut decompressed)?;
        Ok(serde_json::from_slice(&decompressed)?)
    }

    pub fn store(&self, working_dir: &str) -> Result<(), Error> {
        let json = serde_json::to_vec(self)?;
        let mut compressed = vec![];
        let mut gz = GzEncoder::new(&json[..], Compression::new(3));
        gz.read_to_end(&mut compressed)?;

        Ok(write_bytes(
            &join4(working_dir, ".neukgu", "turns", &format!("{}.json.gz", self.id.0))?,
            &compressed,
            WriteMode::Atomic,
        )?)
    }

    pub fn render_llm_response(&self, full_render: bool) -> String {
        if full_render {
            match &self.parse_result {
                Some(ParsedSegment { cot, tool_str: Some(tool_str), .. }) => format!("{cot}{tool_str}"),
                _ => self.raw_response.to_string(),
            }
        } else {
            match &self.parse_result {
                Some(ParsedSegment { tool_str: Some(tool_str), .. }) => tool_str.to_string(),
                _ => self.raw_response.to_string(),
            }
        }
    }

    // `.summary()` is used by be and fe, and `.preview()` is used by fe.
    pub fn summary(&self, config: &Config) -> TurnSummary {
        let result_len = count_bytes_of_llm_tokens(
            &self.turn_result.to_llm_tokens(config),

            // TODO: make it configurable
            /* bytes_per_image: */ 2048,
        );
        let response_len_full = self.render_llm_response(true).len() as u64;
        let response_len_short = self.render_llm_response(false).len() as u64;

        TurnSummary {
            id: self.id.clone(),
            result: self.turn_result.summary(),
            kind: self.kind,
            llm_len_short: result_len + response_len_short,
            llm_len_full: result_len + response_len_full,
        }
    }

    // `.summary()` is used by be and fe, and `.preview()` is used by fe.
    pub fn preview(&self) -> TurnPreview {
        let preview_title = match &self.parse_result {
            Some(parse_result) => {
                match self.kind {
                    TurnKind::Agent | TurnKind::SessionStart => if let Some(tool) = &parse_result.tool {
                        tool.preview()
                    } else {
                        String::from("???")
                    },
                    TurnKind::UserInstruction => match &self.turn_result {
                        TurnResult::ToolCallSuccess(ToolCallSuccess::InstructionFromUser(instruction)) => format!("Instruction from user {:?}", truncate_chars(&instruction.to_string(), 36)),
                        _ => unreachable!(),
                    },
                    // I don't make `parse_result` in this case.
                    TurnKind::UserQuestion => unreachable!(),
                }
            },
            _ if self.kind == TurnKind::UserQuestion => match &self.turn_result {
                TurnResult::ToolCallSuccess(ToolCallSuccess::QuestionFromUser { q, .. }) => format!("Question from user {:?}", truncate_chars(q, 36)),
                _ => unreachable!(),
            },
            _ => String::from("????"),
        };
        let preview_title_truncated = if preview_title.chars().count() > 80 {
            format!("{}...", preview_title.chars().take(76).collect::<String>())
        } else {
            preview_title.to_string()
        };

        TurnPreview {
            id: self.id.clone(),
            preview_title,
            preview_title_truncated,
            result: self.turn_result.summary(),
            llm_elapsed_ms: self.llm_elapsed_ms,
            tool_elapsed_ms: self.tool_elapsed_ms,
            timestamp: TURN_TIMESTAMP_REGEX.captures(&self.id.0).unwrap().get(1).unwrap().as_str().to_string(),
            timestamp_millis: self.timestamp_millis,
        }
    }

    // <read><path>src/</path></read> -> Some(("src/", None))
    // <read><path>src/main.rs</path></read> -> Some(("src/", Some("main.rs")))
    pub fn get_result_path(&self) -> Result<Option<(String, Option<String>)>, Error> {
        match &self.turn_result {
            TurnResult::ParseError(_) => Ok(None),
            TurnResult::ToolCallError(te) => te.get_result_path(),
            TurnResult::ToolCallSuccess(tcs) => tcs.get_result_path(),
        }
    }

    pub fn introduce_agents(&self) -> String {
        fn introduce_agent(model: Model, etc_models: &EtcModels) -> String {
            match model {
                Model::OpenaiEtc1 => format!("{} ({})", model.short_name(), etc_models.openai_etc1_model.as_ref().unwrap_or(&String::from("????"))),
                Model::OpenaiEtc2 => format!("{} ({})", model.short_name(), etc_models.openai_etc2_model.as_ref().unwrap_or(&String::from("????"))),
                Model::OpenaiEtc3 => format!("{} ({})", model.short_name(), etc_models.openai_etc3_model.as_ref().unwrap_or(&String::from("????"))),
                _ => model.short_name().to_string(),
            }
        }

        match self.kind {
            TurnKind::Agent => {
                if let TurnResult::ToolCallSuccess(ToolCallSuccess::Ask { to: AskTo::Web, .. }) = &self.turn_result {
                    if self.agents.search != self.agents.big {
                        return format!(
                            "Agent: {}\nSearch Agent: {}",
                            introduce_agent(self.agents.big, &self.etc_models),
                            introduce_agent(self.agents.search, &self.etc_models),
                        );
                    }
                }

                introduce_agent(self.agents.big, &self.etc_models)
            },
            TurnKind::SessionStart => String::from("Auto-generated"),
            TurnKind::UserQuestion => String::from("User question"),
            TurnKind::UserInstruction => String::from("User instruction"),
        }
    }
}

#[derive(Clone, Debug, Deserialize, Serialize)]
pub enum TurnResult {
    ParseError(ParseError),
    ToolCallError(ToolCallError),
    ToolCallSuccess(ToolCallSuccess),
}

impl TurnResult {
    pub fn to_llm_tokens(&self, config: &Config) -> Vec<LLMToken> {
        match self {
            TurnResult::ParseError(e) => e.to_llm_tokens(config),
            TurnResult::ToolCallError(e) => e.to_llm_tokens(config),
            TurnResult::ToolCallSuccess(r) => r.to_llm_tokens(config),
        }
    }

    pub fn summary(&self) -> TurnResultSummary {
        match self {
            TurnResult::ParseError(_) => TurnResultSummary::ParseError,
            TurnResult::ToolCallError(_) => TurnResultSummary::ToolCallError,
            TurnResult::ToolCallSuccess(_) => TurnResultSummary::ToolCallSuccess,
        }
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Serialize, PartialEq)]
pub enum TurnResultSummary {
    ParseError,
    ToolCallError,
    ToolCallSuccess,
}

#[derive(Clone, Debug)]
pub struct TurnSummary {
    pub id: TurnId,
    pub result: TurnResultSummary,
    pub kind: TurnKind,
    pub llm_len_short: u64,
    pub llm_len_full: u64,
}

pub fn get_turn_id(summary: TurnSummary) -> TurnId {
    let now = Local::now();
    let now = now.to_rfc3339_opts(SecondsFormat::Millis, true);
    TurnId(format!(
        "{now}-{}-{}-{:06}-{:06}",
        match summary.result {
            TurnResultSummary::ParseError => "pe",
            TurnResultSummary::ToolCallError => "tce",
            TurnResultSummary::ToolCallSuccess => "tcs",
        },
        match summary.kind {
            TurnKind::Agent => "ag",
            TurnKind::SessionStart => "ss",
            TurnKind::UserQuestion => "uq",
            TurnKind::UserInstruction => "ui",
        },
        summary.llm_len_short,
        summary.llm_len_full,
    ))
}

#[derive(Clone, Debug)]
pub struct TurnPreview {
    pub id: TurnId,
    pub preview_title: String,
    pub preview_title_truncated: String,
    pub result: TurnResultSummary,
    pub llm_elapsed_ms: u64,
    pub tool_elapsed_ms: u64,

    // When the tool-call ended
    pub timestamp: String,
    pub timestamp_millis: i64,
}
